name: Tadadak
options:
  createIntermediateGroups: true
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 5.9
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    CODE_SIGNING_ALLOWED: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: B2T4ZBL7GM

targets:
  Tadadak:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    info:
      path: Config/Info.plist
      properties:
        CFBundleIdentifier: com.tadadak.app
        LSUIElement: true
        NSHighResolutionCapable: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tadadak.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: B2T4ZBL7GM
          CODE_SIGN_IDENTITY: Apple Development
        Release:
          CODE_SIGN_STYLE: Automatic
          DEVELOPMENT_TEAM: B2T4ZBL7GM
          ENABLE_HARDENED_RUNTIME: YES
    sources:
      - path: Sources/TadadakApp
        excludes:
          - Resources/**
      - path: Sources/TadadakApp/Resources
        type: folder
        buildPhase: resources
    scheme:
      testTargets: []
      build:
        targets:
          Tadadak: all
      run:
        config: Debug
      archive:
        config: Release
